server:
  port: 8082

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecomm_productdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      # timeout for Redis operations
      timeout: 2000ms
      lettuce:
        pool:
          # Connection pool settings
          max-active: 10
          max-idle: 5
          min-idle: 2
  zipkin:
    base-url: http://localhost:9411
    enabled: true

cache:
  product:
    ttl: 600  # 10 minutes in seconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      # Adds service name tag to every metric —
      # essential for filtering in Prometheus/Grafana
      application: ${spring.application.name}
    distribution:
      # Track percentiles for latency metrics
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
  tracing: # 1.0 = 100% sampling — use 0.1 (10%) in production
      sampling:
        probability: 1.0

logging:
  level:
    com.ecommerce: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Must be identical secret to user-service
# — same key signs and verifies
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

